DROP TABLE IF EXISTS raw_web_log;

/*
 * A simple database table to load raw web logs into.  Don't specify any
 * constraints on the columns so that the load will go as fast as possible.
 */
CREATE TABLE raw_web_log (
  -- The IP address (or hostname) of the client requesting the resource.
  ip_addr       VARCHAR(100),

  -- The date and time of the request, in the server's local time.
  logtime       TIMESTAMP,

  -- The timezone of the server's timestamp.
  logtimezone   INTEGER,

  -- The HTTP request method, typically one of GET, PUT, POST, WRITE,
  -- DELETE, etc.
  method        VARCHAR(15),

  -- The path to the specific resource or file being requested.
  resource      VARCHAR(200),

  -- The HTTP protocol version that is specified for the request.
  protocol      VARCHAR(200),

  -- The HTTP response code from the server, e.g. 200 for "OK",
  -- or 404 for "Not found".
  response      INTEGER,

  -- Total bytes sent to the client, for this request.
  bytes_sent    INTEGER,

  -- A unique value assigned to each "visit" to the website.  Since we only know
  -- individual requests, we define a "visit" to be a set of requests from a
  -- particular IP address, that are within 20 minutes of some other request in
  -- the same visit.
  --
  -- These values are generated by the log preprocessing program, since
  -- generating them within the database is prohibitively slow.
  visit_val     INTEGER

) ENGINE = MyISAM;

